### ISSUE TITLE
Развитие проекта

### ISSUE THREAD

**Issue by sanktsankt** [Joomla-Ukraine/CKEditor#2]
Сам давно пользуюсь CKEditor еще с Joomla 1.5. На Joomla 3 делал собственную сборку на базе еще доступного компонента под Joomla 2.5. Версия редактора у меня также 4,4,3 и такой же CK Finder.

Есть ли у вас возможность в своей сборке обновить самое важное - CK Finder до v3.4.4??
у меня не получилось прикрутить новый CK Finder...
ну и вдобавок CK Editor до v4.10.1, хотя это уже мелочи :)

спасибо

**Comment by denysdesign** [comment]
Привет. Пока не особо обновляю, так как в последних версиях не очень удобно работать с вставкой текста из ворда.

Но впринципе можно будет посмотреть.

Буду благодарен за багрепорты и возможно хотелки.

**Comment by denysdesign** [comment]
> Сам давно пользуюсь CKEditor еще с Joomla 1.5. На Joomla 3 делал собственную сборку на базе еще доступного компонента под Joomla 2.5. Версия редактора у меня также 4,4,3 и такой же CK Finder.
> 
> Есть ли у вас возможность в своей сборке обновить самое важное - CK Finder до v3.4.4??
> у меня не получилось прикрутить новый CK Finder...
> ну и вдобавок CK Editor до v4.10.1, хотя это уже мелочи :)
> 
> спасибо

Ловите обновление с новым файловым менеджером!
